### ISSUE TITLE
Weird text widget at bottom?

### ISSUE THREAD

**Issue by fuzzy76** [gistdeck/gistdeck.github.com#4]
A script is loaded from https://oyanglul.us/gulugulu/public/main.min.js which contains a text widget that I really don't understand the purpose of. It is also in a language most of the world doesn't understand.

What is the purpose? What does the textbox do? Is it necessary? Can it be removed?

**Comment by jcouyang** [comment]
it's https://github.com/jcouyang/gulugulu
if you know bilibili or niconico, then it makes sense to you, else ignore it

**Comment by fuzzy76** [comment]
I can ignore it, but I think a permanent bar in a foreign language makes my presentations look bad...

**Comment by jcouyang** [comment]
While I think that make my slides look gorgeous. sorry can not remove that.

You could hide it though if you think it's no cool.

Just open inspect element on browser and delete the widget element

Or, a pull request is more welcomed, with a feature toggle to hide It.
